inhibit_all_warnings!
use_frameworks!
platform :ios, '9.0'

#Workspace
workspace 'TMRelearnModule.xcworkspace'
#主工程
xcodeproj 'TMRelearnModule.xcodeproj'

target 'TMRelearnModule_Example' do
  pod 'TMRelearnModule', :path => '../'

  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'YJNetManager'
  
end

target 'TMRelearnModuleFramework' do
  xcodeproj 'TMRelearnModuleFramework/TMRelearnModuleFramework.xcodeproj'
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'YJNetManager'
  
end
