# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMRelearnModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMRelearnModule

pod 'AFNetworking'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'YJNetManager'
  pod 'SGTools/SGSingleAudioPlayer'
  pod 'SGTools/SGSpeechSynthesizer'
  pod 'SGTools/SGVocabularyDictation'
  pod 'MarqueeLabel', '3.2.0'
  pod 'ReactiveObjC'
  pod 'YJTaskMark'
  pod 'SGTools/SGTriangleView'
  pod 'SGTools/SGVocabularyDictation'
  pod 'SGTools/SGGradientProgress'
  pod 'PSGChainedMode'

end
